# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=500)),
                ('pro_ans', models.CharField(max_length=500)),
                ('sug_ans', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
